// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CheckIDAvail(arg1:number,arg2:number):Promise<boolean>;

export function CheckIDAvailNew(arg1:number):Promise<boolean>;

export function CheckPassword(arg1:string):Promise<boolean>;

export function EditClient(arg1:models.Client):Promise<models.Client>;

export function EditEntry(arg1:models.Entry):Promise<models.Entry>;

export function GetAllClients():Promise<Array<models.Client>>;

export function GetBackUp(arg1:boolean,arg2:string):Promise<void>;

export function GetClientEntries(arg1:number):Promise<Array<models.Entry>>;

export function GetClientSheet(arg1:models.ClientData,arg2:string):Promise<boolean>;

export function GetEntriesBetween(arg1:number,arg2:number):Promise<Array<models.Entry>>;

export function GetSummarySheet(arg1:models.SummaryData,arg2:string):Promise<boolean>;

export function HasPassword():Promise<boolean>;

export function InsertClient(arg1:models.Client):Promise<models.Client>;

export function InsertNewEntry(arg1:models.Entry):Promise<models.Entry>;

export function InsertOldClient(arg1:models.Client):Promise<models.Client>;

export function LogOut():Promise<void>;

export function NewPassword(arg1:string):Promise<boolean>;

export function RecheckPassword(arg1:string):Promise<boolean>;

export function RemoveEntry(arg1:number,arg2:string):Promise<boolean>;

export function RestoreCheck():Promise<models.BackupInfo>;

export function RestoreFromArchive(arg1:models.BackupInfo):Promise<boolean>;

export function SetAppSize(arg1:number,arg2:number):Promise<void>;
