// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIDAvail(arg1, arg2) {
  return ObfuscatedCall(0, [arg1, arg2]);
}

export function CheckIDAvailNew(arg1) {
  return ObfuscatedCall(1, [arg1]);
}

export function CheckPassword(arg1) {
  return ObfuscatedCall(2, [arg1]);
}

export function EditClient(arg1) {
  return ObfuscatedCall(3, [arg1]);
}

export function EditEntry(arg1) {
  return ObfuscatedCall(4, [arg1]);
}

export function GetAllClients() {
  return ObfuscatedCall(5, []);
}

export function GetBackUp(arg1, arg2) {
  return ObfuscatedCall(6, [arg1, arg2]);
}

export function GetClientEntries(arg1) {
  return ObfuscatedCall(7, [arg1]);
}

export function GetClientSheet(arg1, arg2) {
  return ObfuscatedCall(8, [arg1, arg2]);
}

export function GetEntriesBetween(arg1, arg2) {
  return ObfuscatedCall(9, [arg1, arg2]);
}

export function GetSummarySheet(arg1, arg2) {
  return ObfuscatedCall(10, [arg1, arg2]);
}

export function HasPassword() {
  return ObfuscatedCall(11, []);
}

export function InsertClient(arg1) {
  return ObfuscatedCall(12, [arg1]);
}

export function InsertNewEntry(arg1) {
  return ObfuscatedCall(13, [arg1]);
}

export function InsertOldClient(arg1) {
  return ObfuscatedCall(14, [arg1]);
}

export function LogOut() {
  return ObfuscatedCall(15, []);
}

export function NewPassword(arg1) {
  return ObfuscatedCall(16, [arg1]);
}

export function RecheckPassword(arg1) {
  return ObfuscatedCall(17, [arg1]);
}

export function RemoveEntry(arg1, arg2) {
  return ObfuscatedCall(18, [arg1, arg2]);
}

export function RestoreCheck() {
  return ObfuscatedCall(19, []);
}

export function RestoreFromArchive(arg1) {
  return ObfuscatedCall(20, [arg1]);
}

export function SetAppSize(arg1, arg2) {
  return ObfuscatedCall(21, [arg1, arg2]);
}
